#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# use flaccid's fork until http://tickets.opscode.com/browse/COOK-2820 is complete by PR
cookbook 'openvpn',
  :git => 'https://github.com/flaccid/openvpn',
  :ref => 'master'

cookbook 'system',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/system',
   :ref => 'master'

cookbook 'rightscale',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/rightscale',
   :ref => 'master'

cookbook 'resolver',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/resolver',
   :ref => 'master'

cookbook 'cron',
  :git => 'https://github.com/opscode-cookbooks/cron',
  :ref => 'master'

cookbook 'ntp',
  :git => 'https://github.com/opscode-cookbooks/ntp',
  :ref => 'master'
   
cookbook 'sudo',
  :git => 'https://github.com/opscode-cookbooks/sudo',
  :ref => 'master'

# currently using un-pushed flaccid fork
cookbook 'collectd',
  :git => 'https://github.com/flaccid/chef-collectd',
  :ref => 'master'
#cookbook 'collectd',
#  :git => 'https://github.com/coderanger/chef-collectd',
#  :ref => 'master'

cookbook 'collectd_plugins',
  :git => 'https://github.com/coderanger/chef-collectd_plugins',
  :ref => 'master'